config/routes.rb
Outsidein::Application.routes.draw do
  root to: 'libraries#index'
  match "/libraries/:id/books/new" => "libraries#add_book", as: "add_library_book", via: [:get, :put]
  resources :libraries
  resources :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :libraries, join_table: "libraries_books"
end

app/models/library.rb
class Library < ActiveRecord::Base
  attr_accessible :name, :built_date
  has_and_belongs_to_many :books, join_table: "libraries_books"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    respond_to do |format|
      format.html
      format.json {render json: @books }
    end
  end
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(params[:book])
    if @book.save
      redirect_to books_path
    end
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def index
    @libraries = Library.all
  end

  def show
    @library = Library.find(params[:id])
    @books = @library.books
  end

  def new
    @library = Library.new
  end

  def add_book
    @library = Library.find(params[:id])
    if request.put?
      book = Book.find(params[:book_id])
      @library.books << book
      redirect_to @library
    end
    
  end

  def create
    @library = Library.new(params[:library])
    if @library.save
      redirect_to @library
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/books/_book.html.haml
%li= book.name

app/views/books/index.html.haml
%h2 List books!
= render partial: @books
= link_to "New book", new_book_path

app/views/books/new.html.haml
%h1 New book
= form_for @book do |f|
  = f.label :name, "Name"
  = f.text_field :name
  = f.submit "Create", disable_with: 'Creating...'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Outsidein</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/libraries/add_book.html.haml
%h1= @library.name

= form_for @library, :url => { :action => "add_book" } do |f| 
  = select_tag(:book_id, options_from_collection_for_select(Book.where('id not in (?)', @library.books.empty? ? '': @library.books), :id, :name))
  = f.submit "Add Book"
%hr
= link_to "Go back to library info", @library
  

app/views/libraries/index.html.haml
%h1 List of libraries
%ul
- @libraries.each do |l|
  %li= link_to "#{l.name} (#{l.built_date})", l
= link_to "Add Library", new_library_path

app/views/libraries/new.html.haml
%h1 New library
= form_for @library do |f|
  = f.label :name, "Name"
  = f.text_field :name
  = f.label :built_date, "Build Date"
  = f.number_field :built_date
  = f.submit "Create", disable_with: 'Creating...'

app/views/libraries/show.html.haml
%h1 Books for #{@library.name} built in #{@library.built_date}
%h2 Books in this library
%ul
-@books.each do |b|
  %li= b.name

= link_to("Add book to library", add_library_book_path(@library))
%hr
= link_to "Back to library list", libraries_path